<?php

use Drupal\Core\Form\FormStateInterface;

/* function cardform_form_node_form_alter() {}; */

/* function cardform_theme($existing, $type, $theme, $path) {
  return array(
    'cardform' => array(
      'variables' => array(
        'company' => NULL,
        'job' => NULL,
        'name' => NULL,
		'last name' => NULL,
		'adresse' => NULL,
		'num' => NULL,
		'email' => NULL,
		
      ),
    ),
  );
} */

/* function cardform_theme($existing, $type, $theme, $path) {
  return array(
    'node--business-cards--full' => array(
      'variables' => array(
			'company' => NULL, 
			'job' => NULL,
			'name' => NULL,
			'lastname' => NULL,
			'adress' => NULL,
			'num' => NULL,
			'email' => NULL,
      ),
    ),
  );
} */


function cardform_theme($existing, $type, $theme, $path) {
  return array(
    'business_cards' => array(
		'template' => 'node--business-cards--full',
		'variables' => array(
			'company' => NULL, 
			'job' => NULL,
			'name' => NULL,
			'lastname' => NULL,
			'address' => NULL,
			'num' => NULL,
			'email' => NULL,		
		),
    ),
  );
}


function multivaluefield_theme_suggestions_multivaluefield($variables) {

  $suggestions = array();
  $sett = $variables['settings'];

  $suggestions[] = 'multivaluefield__' . $sett['#field_name'];
  $suggestions[] = 'multivaluefield__' . $sett['#entity_type'];
  $suggestions[] = 'multivaluefield__' . $sett['#bundle'];
  $suggestions[] = 'multivaluefield__' . $sett['#field_name'] . '__' . $sett['#entity_type'] . '__' . $sett['#bundle'];

  return $suggestions;
}



/* function cardform_form_node_form_alter(&$form, FormStateInterface $form_state) {
  kint($variables);
  exit;
}
  */
/* function cardform_node_form_submit($form, FormStateInterface $form_state) {
   $node = $form_state->getFormObject()->getEntity();
kint($node);
exit;
} */

