<?php

use Drupal\Core\Form\FormStateInterface;

/* function cardform_form_node_form_alter() {}; */

/* function cardform_node_edit_form_alter() {}; */

function cardform_theme($existing, $type, $theme, $path) {
  return array(
        'business_cards' => array(
            'template' => 'node--business-cards--full',
            'variables' => array(
                'company' => NULL,
                'job' => NULL,
                'name' => NULL,
                'lastname' => NULL,
                'address' => NULL,
                'num' => NULL,
                'email' => NULL,
            ),
        ),
        'postal_cards' => array(
            'template' => 'node--postal-cards--full',
            'variables' => array(
                'ptimodou' => NULL,
                'recto' => NULL,
                'verso' => NULL,
                'nouvelles' => NULL,
                'nom' => NULL,
                'prenom' => NULL,
                'addresse' => NULL,
            ),
        ),
        'game_cards' => array(
            'template' => 'node--game-cards--full',
            'variables' => array(
                'company' => NULL,
                'job' => NULL,
                'name' => NULL,
                'lastname' => NULL,
                'address' => NULL,
                'num' => NULL,
                'email' => NULL,
            ),
        ),
  );

}

function multivaluefield_theme_suggestions_multivaluefield($variables) {

  $suggestions = array();
  $sett = $variables['settings'];

  $suggestions[] = 'multivaluefield__' . $sett['#field_name'];
  $suggestions[] = 'multivaluefield__' . $sett['#entity_type'];
  $suggestions[] = 'multivaluefield__' . $sett['#bundle'];
  $suggestions[] = 'multivaluefield__' . $sett['#field_name'] . '__' . $sett['#entity_type'] . '__' . $sett['#bundle'];

  return $suggestions;
}

function cardform_form_node_form_alter(&$form, $form_state, $form_id) {

}
